spring:
  application:
    name: Taskora
  datasource:
    url: jdbc:h2:file:${USERPROFILE}\taskora\db\taskora.db;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
